[package]
name = "parser"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8.0"
# cached = "0.34.0"
lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions = "1.2.1"